### ISSUE TITLE
Do i still need MixinBootstrap?

### ISSUE THREAD

**Issue by girshcatt** [yezhiyi9670/occlusion-culling-fix#2]
Do i still need MixinBootstrap if I am playing 1.16.5 with latest forge 36.2.42?
I have already tried your fix with MixinBootstrap and it works, but maybe MixinBootstrap is unnecessary on latest 1.16.5 forge, because Mixin is available in Forge 1.15.2-31.2.44+ & 1.16.1-32.0.72+?

**Comment by yezhiyi9670** [comment]
I guess it is not needed.
